version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
    depends_on:
      - node-exporter
      - alertmanager

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring-net

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-net
    restart: always
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.your-email-provider.com:587
      - GF_SMTP_USER=your-email@example.com
      - GF_SMTP_PASSWORD=your-email-app-password
      - GF_SMTP_FROM_ADDRESS=your-email@example.com
      - GF_SMTP_FROM_NAME=YourAppName
      - GF_SMTP_SKIP_VERIFY=false

networks:
  monitoring-net:
    driver: bridge

volumes:
  grafana-storage:
